### ISSUE TITLE
Example for "app" cookbook

### ISSUE THREAD

**Issue by dev-head** [Nordstrom/chef-gen-flavor-example#6]
Love the flavors, any chance you are going to release an example that creates an app? 

```
chef generate app myApp
```

**Comment by jf647** [comment]
We don't tend to use the ChefDK app generator at Nordstrom, so I didn't have plans to add it.  If I did, it would probably just be an adaptation of the one that comes with ChefDK.  We do have plans to add a repo recipe, but the first release was mostly centered around individual cookbooks.

**Comment by dev-head** [comment]
@jf647  thanks for the reply, Looks like it's time to crack my knuckles and get back to work.
